version: 2
jobs:
  build:
    docker:
    - image: ncino/ci-sfdx-lite:latest
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Create auth token
        command: echo $SFDC_AUTH > hubauth.txt
    - run:
        name: Authenticate to Hub Org
        command: sfdx force:auth:sfdxurl:store --setdefaultdevhubusername --sfdxurlfile hubauth.txt
    - run:
        name: Remove auth token
        command: rm hubauth.txt
    - run:
        name: Delete prev Scratch Org (ignoring bash return code) in case of previous failure
        command: sfdx force:org:delete --noprompt --targetusername circleci || true
    - run:
        name: Create Scratch Org
        command: sfdx force:org:create --definitionfile config/project-scratch-def.json --durationdays 1 --setdefaultusername --setalias circleci
    - run:
        name: Install Lightning Testing Service package
        command: sfdx force:lightning:test:install
    - run:
        name: Deploy Source
        command: sfdx force:source:push
    - run:
        name: Run Apex Tests
        command: |
          mkdir -p ~/junit
          sfdx force:apex:test:run --codecoverage --outputdir ~/junit --resultformat junit --wait 5
    - store_test_results:
        path: ~/junit
    - run:
        name: Delete Scratch Org (ignoring bash return code)
        command: sfdx force:org:delete --noprompt --targetusername circleci || true
